language: php

php:
  - 7.0
  - 7.1

before_script:
  - touch database/rfid.sqlite
  - cp .env.travis .env
  - composer self-update
  - composer install --no-interaction
  - php artisan migrate
  - php artisan db:seed

script:
  - vendor/bin/phpunit