name: PHP Composer
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
      matrix:
        php: ['7.4']
    name: PHP ${{ matrix.php }}
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: rfid
        ports:
          - 3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout Code
        uses: actions/checkout@v1

      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: ~/.composer/cache/files
          key: dependencies-php-${{ matrix.php }}-composer-${{ hashFiles('composer.json') }}

      - name: Setup PHP
        uses: shivammathur/setup-php@2.9.0
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, mysql, mysqli, pdo_mysql, bcmath, soap, intl, gd, exif, iconv, imagick
          coverage: none

      - name: Report PHP version
        run: cp .env.example .env

      - name: Install dependencies & Setup App
        run: |
          composer install && php artisan key:generate --ansi && php artisan migrate --force && php artisan db:seed --force
        env:
            DB_PORT: ${{ job.services.mysql.ports[3306] }}

      - name: Execute tests
        run: vendor/bin/phpunit
        env:
          DB_PORT: ${{ job.services.mysql.ports[3306] }}

      - name: Cat Log
        run: cat storage/logs/laravel.log
        if: ${{ failure() }}

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
        if: ${{ success() }} && $GITHUB_REF == 'refs/heads/master'

#      - name: Deploy
#        run: vendor/bin/envoy run deploy
#        if: ${{ success() }} && $GITHUB_REF == 'refs/heads/master'
      - name: Deploy
        run: echo $GITHUB_REF && echo ${{ success() }}
        if: ${{ success() }} && $GITHUB_REF == 'refs/heads/master'